server:
  port: 8083
logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
---
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://u3uhq5ibggo0mnvb:5GJNQ0ZzpzBWFfFhitlG@b0oyypcm81idyjhfvbqg-mysql.services.clever-cloud.com:3306/b0oyypcm81idyjhfvbqg
    username: u3uhq5ibggo0mnvb
    password: 5GJNQ0ZzpzBWFfFhitlG
    hikari:
      connectionTimeout: 60000
      idleTimeout: 600000
      maxLifetime: 1800000
      maximumPoolSize: 20
      connectionTestQuery: SELECT 1 FROM DUAL
springdoc:
  swagger-ui:
    enabled: true